# GLOBAL SITE SETTINGS

cname: workskil.yourwebvisual.com

# META
title: Workskil Australia
company: Workskil Australia
description:

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/wrksl-1116
jekyll_version: 3.8.5

# OFFICES
offices:
  - title: Head Office
    address: Level 1, 1069 South Road<br>Melrose Park, SA 5039
    phone: 1800 125 555
    email: workskil@workskil.com.au
    fax: 08 7088 8099
    po_box: PO Box 433<br>Melrose Park, SA 5039

# GOOGLE
google_analytics: "UA-XXXXXXXX-X"
google_map:

# AUTHOR
author:
  title: Much Media
  url: https://muchmedia.com.au
  logo: /assets/img/ui/much-media-logo.svg
  description: Website by Much Media